[package]
name = "ttrpc"
version = "0.2.0"
authors = ["The AntFin Kata Team <kata@list.alibaba-inc.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["ttrpc", "protobuf", "rpc"]
readme = "README.md"
repository = "https://github.com/alipay/ttrpc-rust"
homepage = "https://github.com/alipay/ttrpc-rust"
description = "A Rust version of ttrpc."

[dependencies]
protobuf = { version = "2.0", optional = true }
bytes = { version = "0.4.11", optional = true }
libc = { version = "0.2.59", features = [ "extra_traits" ] }
nix = "0.15.0"
log = "0.4"
byteorder = "1.3.2"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf"]

