[package]
name = "ttrpc-compiler"
version = "0.2.0"
edition = "2018"
authors = ["The AntFin Kata Team <kata@list.alibaba-inc.com>"]
license = "Apache-2.0"
keywords = ["compiler", "ttrpc", "protobuf"]
description = "ttRPC compiler for ttrpc"
categories = ["network-programming"]

[dependencies]
protobuf = "2.0"
protobuf-codegen = "2.0"
prost = "0.5"
prost-build = "0.5"
prost-types = "0.5"
derive-new = "0.5"
tempfile = "3.0"

[[bin]]
name = "ttrpc_rust_plugin"
